import React from "react";
const H1 = (props) => { return <h1 className={props.className} {...props}>{props.children}</h1>;};
const H2 = (props) => { return <h2 className={props.className} {...props}>{props.children}</h2>;};
const H3 = (props) => { return <h3 className={props.className} {...props}>{props.children}</h3>;};
const Paragraph = (props) => { return <p className={props.className} {...props}>{props.children}</p>;};
const Block = (props) => { return <div className={props.className} {...props}>{props.children}</div>;};
const Text = (props) => { return <span className={props.className} {...props}>{props.children}</span>;};
const Label = (props) => { return <label htmlFor={props.for} className={props.className} {...props}>{props.children}</label>;};
const List = (props) => { return <ul className={props.className} {...props}>{props.children}</ul>;};
export { H1, H2, H3, Paragraph, Block, Text, Label, List };
